theme = "catppuccin_mocha"

[editor]
line-number = "relative"
scrolloff = 999
auto-save = true
auto-format = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.normal.space.c]
f = ":fmt"